-- Auto-generated SQLite schema from CSV files in this repository.
-- Review inferred types for edge cases before loading production data.
PRAGMA foreign_keys = OFF;

-- Source: epaCC-START-Hack-2026-main/Endtestdaten_mit_Fehlern_ einheitliche ID/epaAC-Data-3.csv
-- Encoding: cp1252, Delimiter: ';', Header detected: True, Sample data rows: 40
DROP TABLE IF EXISTS "epaac_data_3";
CREATE TABLE "epaac_data_3" (
    "EinschIDFall" TEXT,
    "FallNr (STRING)" TEXT,
    "AufnDat" TEXT,
    "AufnZeit" TEXT,
    "EntlassDat" TEXT,
    "EntlassZeit" TEXT,
    "EinschDat" TEXT,
    "EinschZeit" TEXT,
    "FaBerFaAbt (STRING)" TEXT,
    "StatBez (STRING)" TEXT,
    "InstrVers" TEXT,
    "Einschätzungstyp" TEXT,
    "Versorgungsform zu Hause/ vor Eintritt" TEXT,
    "Fremdsprachigkeit (STRING)" TEXT,
    "Fremdsprachigkeit" TEXT,
    "Fremdsprachigkeit Bezugsperson (STRING)" TEXT,
    "Fremdsprachigkeit Bezugsperson" TEXT,
    "Körpergröße" TEXT,
    "Körpergewicht" TEXT,
    "Ungewollter Gewichtsverlust" TEXT,
    "BMI" TEXT,
    "BMI beeinflussende Faktoren" TEXT,
    "Nahrungsmenge vor Aufnahme" TEXT,
    "Alter" TEXT,
    "Pflegegrad gem. §15 SGB XI (Pflegeversicherung)" TEXT,
    "Pflegegrad ist beantragt (OPS 9-984.b)" TEXT,
    "Hilfsmittel Fortbewegung/Mobilität (Beschreibung) (STRING)" TEXT,
    "Hilfsmittel Fortbewegung/Mobilität (n.b.)" TEXT,
    "Hilfsmittel Fortbewegung/Mobilität (4: Keine)" TEXT,
    "Hilfsmittel Fortbewegung/Mobilität (1f: Andere)" TEXT,
    "Hilfsmittel Fortbewegung/Mobilität (1e: Hilfsmittel zum Heben von Personen)" TEXT,
    "Hilfsmittel Fortbewegung/Mobilität (1d: Transfer- und Wendehilfen)" TEXT,
    "Hilfsmittel Fortbewegung/Mobilität (1c: Rollstuhl)" TEXT,
    "Hilfsmittel Fortbewegung/Mobilität (1b: Mit beiden Armen gehandhabte Gehhilfen)" TEXT,
    "Hilfsmittel Fortbewegung/Mobilität (1a: Mit einem Arm gehandhabte Gehhilfen)" TEXT,
    "Prothesen/ Orthesen (STRING)" TEXT,
    "Prothesen/ Orthesen" TEXT,
    "Hilfsmittel Körperpflege (STRING)" TEXT,
    "Hilfsmittel Körperpflege" TEXT,
    "Hilfsmittel Kleiden (STRING)" TEXT,
    "Hilfsmittel Kleiden" TEXT,
    "Hilfsmittel Ernährung (n.b.)" TEXT,
    "Hilfsmittel Ernährung (Beschreibung) (STRING)" TEXT,
    "Hilfsmittel Ernährung (1b: Andere)" TEXT,
    "Hilfsmittel Ernährung (1a: Zahnprothese)" TEXT,
    "Hilfsmittel Ernährung (4: Keine)" TEXT,
    "Hilfsmittel Ernährung (Beschreibung) (STRING)__2" TEXT,
    "Hilfsmittel Ernährung (n.b.)__2" TEXT,
    "Hilfsmittel Ernährung (4: Keine)__2" TEXT,
    "Hilfsmittel Ernährung (1c: Andere)" TEXT,
    "Hilfsmittel Ernährung (1b: Zahnprothese)" TEXT,
    "Hilfsmittel Ernährung (1a: Zahnspange)" TEXT,
    "Hilfsmittel Ausscheidung (exkl. Ableitungssyst.) (Beschreibung) (STRING)" TEXT,
    "Hilfsmittel Ausscheidung (exkl. Ableitungssyst.) (n.b.)" TEXT,
    "Hilfsmittel Ausscheidung (exkl. Ableitungssyst.) (4: Keine)" TEXT,
    "Hilfsmittel Ausscheidung (exkl. Ableitungssyst.) (1c: Andere)" TEXT,
    "Hilfsmittel Ausscheidung (exkl. Ableitungssyst.) (1b: Inkontinenzmaterialien)" TEXT,
    "Hilfsmittel Ausscheidung (exkl. Ableitungssyst.) (1a: Toilettenhilfen)" TEXT,
    "Hilfsmittel Hören (Beschreibung) (STRING)" TEXT,
    "Hilfsmittel Hören (n.b.)" TEXT,
    "Hilfsmittel Hören (4: Keine)" TEXT,
    "Hilfsmittel Hören (1b: Andere)" TEXT,
    "Hilfsmittel Hören (1a: Hörgerät)" TEXT,
    "Hilfsmittel Sehen (Beschreibung) (STRING)" TEXT,
    "Hilfsmittel Sehen (n.b.)" TEXT,
    "Hilfsmittel Sehen (4: Keine)" TEXT,
    "Hilfsmittel Sehen (1c: Andere)" TEXT,
    "Hilfsmittel Sehen (1b: Kontaktlinsen)" TEXT,
    "Hilfsmittel Sehen (1a: Brille)" TEXT,
    "Hilfsmittel Sprechen/ Nahkommunikation (STRING)" TEXT,
    "Hilfsmittel Sprechen/ Nahkommunikation" TEXT,
    "Patientenverfügung/ Vorausverfügung" TEXT,
    "Bekannter Diabetes Mellitus" TEXT,
    "Freitext Zusatzvariable (STRING)" TEXT,
    "Positionswechsel im Liegen" TEXT,
    "column_76" TEXT,
    "column_77" TEXT,
    "Sitzposition halten" TEXT,
    "column_79" TEXT,
    "column_80" TEXT,
    "Transfer" TEXT,
    "column_82" TEXT,
    "column_83" TEXT,
    "Fortbewegung" TEXT,
    "column_85" TEXT,
    "column_86" TEXT,
    "Reibung/ Scherkräfte bei Positionswechsel/ Transfer" TEXT,
    "column_88" TEXT,
    "column_89" TEXT,
    "Verändertes Gangbild" TEXT,
    "column_91" TEXT,
    "column_92" TEXT,
    "Gleichgewichtsstörungen" TEXT,
    "column_94" TEXT,
    "column_95" TEXT,
    "Sturzvorgeschichte" TEXT,
    "Aktuelles Sturzereignis" TEXT,
    "Erschöpfung/ Fatigue" TEXT,
    "column_99" TEXT,
    "column_100" TEXT,
    "Freitext Kategorie Bewegung (STRING)" TEXT,
    "Körperpflege Oberkörper" TEXT,
    "column_103" TEXT,
    "column_104" TEXT,
    "Körperpflege Unterkörper" TEXT,
    "column_106" TEXT,
    "column_107" TEXT,
    "Mundstatus" TEXT,
    "column_109" TEXT,
    "column_110" TEXT,
    "An-/Auskleiden Oberkörper" TEXT,
    "column_112" TEXT,
    "column_113" TEXT,
    "An-/Auskleiden Unterkörper" TEXT,
    "column_115" TEXT,
    "column_116" TEXT,
    "Freitext Kategorie Körperpflege und Kleiden (STRING)" TEXT,
    "Essen" TEXT,
    "column_119" TEXT,
    "column_120" TEXT,
    "Nahrungsmenge (oral)" TEXT,
    "column_122" TEXT,
    "column_123" TEXT,
    "Künstliche Ernährung/ verordnete Zusatzkost" TEXT,
    "column_125" TEXT,
    "column_126" TEXT,
    "Energie-/ Nährstoffbedarf" TEXT,
    "Nahrungsmenge (gesamt)" TEXT,
    "column_129" TEXT,
    "column_130" TEXT,
    "Trinken" TEXT,
    "column_132" TEXT,
    "column_133" TEXT,
    "Trinkmenge" TEXT,
    "column_135" TEXT,
    "column_136" TEXT,
    "Verhältnis Flüssigkeitsmenge zu Flüssigkeitsbedarf" TEXT,
    "column_138" TEXT,
    "column_139" TEXT,
    "Flüssigkeitsergänzung" TEXT,
    "column_141" TEXT,
    "column_142" TEXT,
    "Sondenernährung" TEXT,
    "column_144" TEXT,
    "column_145" TEXT,
    "Schluckstörungen" TEXT,
    "column_147" TEXT,
    "column_148" TEXT,
    "Übelkeit" TEXT,
    "column_150" TEXT,
    "column_151" TEXT,
    "Freitext Kategorie Ernährung (STRING)" TEXT,
    "Urinausscheidung durchführen" TEXT,
    "column_154" TEXT,
    "column_155" TEXT,
    "Urinausscheidung kontrollieren" TEXT,
    "column_157" TEXT,
    "column_158" TEXT,
    "Urinableitungssystem" TEXT,
    "column_160" TEXT,
    "column_161" TEXT,
    "Stuhlausscheidung durchführen" TEXT,
    "column_163" TEXT,
    "column_164" TEXT,
    "Stuhlausscheidung kontrollieren" TEXT,
    "column_166" TEXT,
    "column_167" TEXT,
    "Stuhlveränderung" TEXT,
    "column_169" TEXT,
    "column_170" TEXT,
    "Stuhlableitungssystem" TEXT,
    "Dranghafte/ gesteigerte Ausscheidung" TEXT,
    "Feuchtigkeit der Haut" TEXT,
    "column_174" TEXT,
    "column_175" TEXT,
    "Freitext Kategorie Ausscheidung (STRING)" TEXT,
    "Bewusstsein/ Vigilanz" TEXT,
    "Orientierung (Person, Ort, Zeit, Situation)" TEXT,
    "column_179" TEXT,
    "column_180" TEXT,
    "Informationen verarbeiten/ verstehen" TEXT,
    "column_182" TEXT,
    "column_183" TEXT,
    "Alltagskompetenz" TEXT,
    "column_185" TEXT,
    "column_186" TEXT,
    "Aufmerksamkeit" TEXT,
    "column_188" TEXT,
    "column_189" TEXT,
    "Sturz-/ Delir-Risiko erhöhende Medikamente" TEXT,
    "Freitext Kategorie Kognition, Bewusstsein (STRING)" TEXT,
    "Hören" TEXT,
    "Sehen" TEXT,
    "Sich mitteilen" TEXT,
    "column_195" TEXT,
    "column_196" TEXT,
    "Selbst initiierte Aktivitäten" TEXT,
    "column_198" TEXT,
    "column_199" TEXT,
    "Merkmale herausfordernden Verhaltens" TEXT,
    "column_201" TEXT,
    "column_202" TEXT,
    "Freitext Kategorie Kommunikation und Interaktion (STRING)" TEXT,
    "Einschlafen/ Durchschlafen" TEXT,
    "column_205" TEXT,
    "column_206" TEXT,
    "Schlaf-Wach-Rhythmus" TEXT,
    "column_208" TEXT,
    "column_209" TEXT,
    "Freitext Kategorie Schlaf (STRING)" TEXT,
    "Atmung beeinträchtigt (aktuell)" TEXT,
    "Chron. Erkrankung des Atmungssystems" TEXT,
    "Beatmung > 24h akt. Aufenthalt" TEXT,
    "Tracheostoma" TEXT,
    "Experteneinschätzung: weitere Pneumonie-Risikoindikatoren (STRING)" TEXT,
    "Experteneinschätzung: weitere Pneumonie-Risikoindikatoren" TEXT,
    "Freitext Kategorie Regulation von Körperfunktionen (STRING)" TEXT,
    "Sensorische Wahrnehmung" TEXT,
    "column_219" TEXT,
    "column_220" TEXT,
    "Schmerzintensität" TEXT,
    "column_222" TEXT,
    "column_223" TEXT,
    "Schmerzen, akut" TEXT,
    "column_225" TEXT,
    "column_226" TEXT,
    "Chronische Schmerzen" TEXT,
    "Schmerzen, chronisch" TEXT,
    "Traurigkeit (STRING)" TEXT,
    "Traurigkeit" TEXT,
    "column_231" TEXT,
    "column_232" TEXT,
    "Angst (STRING)" TEXT,
    "Angst" TEXT,
    "column_235" TEXT,
    "column_236" TEXT,
    "Freitext Kategorie Schmerz und emotionales Befinden (STRING)" TEXT,
    "Experteneinschätzung: weitere Dekubitus-Risikoindikatoren (STRING)" TEXT,
    "Experteneinschätzung: weitere Dekubitus-Risikoindikatoren" TEXT,
    "Dekubitus_Lokalisation" TEXT,
    "Dekubitus_Stadium" TEXT,
    "Dekubitus_Lokalisation__2" TEXT,
    "Dekubitus-Stadium" TEXT,
    "column_244" TEXT,
    "column_245" TEXT,
    "column_246" TEXT,
    "column_247" TEXT,
    "column_248" TEXT,
    "Wunden/ path. Hautveränderungen ([Beschreibung - Freitext]) (STRING)" TEXT,
    "Wunden/ path. Hautveränderungen" TEXT,
    "Wunden/ path. Hautveränderungen ([Beschreibung - Freitext]) (STRING)__2" TEXT,
    "Wunden/ path. Hautveränderungen__2" TEXT,
    "Freitext Kategorie Dekubitus, Wunden (STRING)" TEXT,
    "SPI" TEXT,
    "Risiko Dekubitus: Bradenskala (Punktwert)" TEXT,
    "Risiko Dekubitus: Bradenskala" TEXT,
    "Risiko Dekubitus: weitere Risikoindikatoren (Experteneinschätzung) (STRING)" TEXT,
    "Risiko Dekubitus: weitere Risikoindikatoren (Experteneinschätzung)" TEXT,
    "Risiko Mangelernährung: NRS" TEXT,
    "Risiko Mangelernährung: NRS (Punktwert)" TEXT,
    "Abklärungserfordernis Mundgesundheit" TEXT,
    "Risiko Sturz" TEXT,
    "Risiko Pneumonie" TEXT,
    "Risiko Pneumonie: weitere Risikoindikatoren (Experteneinschätzung) (STRING)" TEXT,
    "Risiko Pneumonie: weitere Risikoindikatoren (Experteneinschätzung)" TEXT,
    "Abklärungserfordernis neurokognitive Störung" TEXT,
    "Risiko poststationäres Versorgungsdefizit" TEXT,
    "Kontinenzprofil" TEXT,
    "Freitext Risikoauswertung (STRING)" TEXT,
    "column_270" TEXT,
    "column_271" TEXT,
    "column_272" TEXT,
    "column_273" TEXT,
    "column_274" TEXT,
    "column_275" TEXT,
    "column_276" TEXT,
    "column_277" TEXT,
    "column_278" TEXT,
    "column_279" TEXT,
    "column_280" TEXT,
    "BMI-Perzentile" TEXT,
    "BMI-Perzentile (EU)" TEXT,
    "BMI-Perzentile Grenzwert unterschritten" TEXT,
    "Gewichtsverlust" TEXT,
    "Nahrungszufuhr vergangene Woche" TEXT,
    "Ernährung kommende Woche" TEXT,
    "Selbstständiges Drehen" TEXT,
    "column_288" TEXT,
    "column_289" TEXT,
    "Selbstständiges Sitzen" TEXT,
    "column_291" TEXT,
    "column_292" TEXT,
    "Sicherer Stand" TEXT,
    "column_294" TEXT,
    "column_295" TEXT,
    "Freies Laufen" TEXT,
    "column_297" TEXT,
    "column_298" TEXT,
    "Altersentsprechende Entwicklung des Kindes" TEXT,
    "Altersentsprechende Entwicklung des Kindes__2" TEXT,
    "Stillen" TEXT,
    "column_302" TEXT,
    "column_303" TEXT,
    "Deckung des Tagesbedarfs (Nährstoffe und Flüssigkeit)" TEXT,
    "column_305" TEXT,
    "column_306" TEXT,
    "Verordnete Flüssigkeitsergänzung" TEXT,
    "column_308" TEXT,
    "column_309" TEXT,
    "Saugverhalten" TEXT,
    "column_311" TEXT,
    "column_312" TEXT,
    "Erbrechen" TEXT,
    "column_314" TEXT,
    "column_315" TEXT,
    "Altersentsprechende Entwicklung des Kindes__3" TEXT,
    "Blähungen" TEXT,
    "column_318" TEXT,
    "column_319" TEXT,
    "Altersentsprechende Entwicklung des Kindes__4" TEXT,
    "Aufforderungen verstehen" TEXT,
    "column_322" TEXT,
    "column_323" TEXT,
    "Altersentsprechende Entwicklung des Kindes__5" TEXT,
    "Merkmale herausfordernden Verhaltens (< 4 J)" TEXT,
    "column_326" TEXT,
    "column_327" TEXT,
    "Fähigkeit veränderte Lebenssituationen zu bewältigen (Kind)" TEXT,
    "column_329" TEXT,
    "column_330" TEXT,
    "Altersentsprechende Entwicklung des Kindes__6" TEXT,
    "Altersentsprechende Entwicklung des Kindes__7" TEXT,
    "Experteneinsch. Pneumonierisiko (STRING)" TEXT,
    "Experteneinsch. Pneumonierisiko" TEXT,
    "Körpertemperatur" TEXT,
    "column_336" TEXT,
    "column_337" TEXT,
    "Altersentsprechende Entwicklung des Kindes__8" TEXT,
    "Schmerzintensität__2" TEXT,
    "column_340" TEXT,
    "column_341" TEXT,
    "Heimweh" TEXT,
    "column_343" TEXT,
    "column_344" TEXT,
    "Altersentsprechende Entwicklung des Kindes__9" TEXT,
    "Experteneinsch. Dekubitusrisiko (STRING)" TEXT,
    "Experteneinsch. Dekubitusrisiko" TEXT,
    "Kompensatorische Fähigkeit Bezugsperson" TEXT,
    "column_349" TEXT,
    "column_350" TEXT,
    "Kompensatorische Übernahme Bezugsperson" TEXT,
    "column_352" TEXT,
    "column_353" TEXT,
    "Fähigkeit veränderte Lebenssituationen zu bewältigen (Bezugsperson/ Familie)" TEXT,
    "column_355" TEXT,
    "column_356" TEXT,
    "Stressüberlastung der Bezugsperson/ Familie - Herausforderung für Pflege" TEXT,
    "column_358" TEXT,
    "column_359" TEXT,
    "Freitext Kategorie Bezugsperson (STRING)" TEXT,
    "SSI" TEXT,
    "Risiko Dekubitus: Experteneinschätzung (STRING)" TEXT,
    "Risiko Dekubitus: Experteneinschätzung" TEXT,
    "Risiko Dehydratation" TEXT,
    "Abklärungserfordernis Mangelernährung" TEXT,
    "Risiko Mangelernährung: PYMS (STRING)" TEXT,
    "Risiko Mangelernährung: PYMS" TEXT,
    "Risiko Pneumonie: Experteneinschätzung (STRING)" TEXT,
    "Risiko Pneumonie: Experteneinschätzung" TEXT,
    "Kompensatorische Fähigkeit Bezugsperson__2" TEXT,
    "Kompensatorische Übernahme Bezugsperson__2" TEXT,
    "Trennung der Eltern" TEXT,
    "Hochstrittige Eltern" TEXT,
    "Aktuelle Wohnsituation (STRING)" TEXT,
    "Aktuelle Wohnsituation" TEXT,
    "Schulbesuch, Ausbildung, Erwerbstätigkeit (STRING)" TEXT,
    "Schulbesuch, Ausbildung, Erwerbstätigkeit" TEXT,
    "Gesetzliche Betreuung/ Gesetzliche Vertretung (STRING)" TEXT,
    "Gesetzliche Betreuung/ Gesetzliche Vertretung" TEXT,
    "Vertrauensperson (STRING)" TEXT,
    "Vertrauensperson" TEXT,
    "Vorgeschichte suizidalen Verhaltens" TEXT,
    "Aktueller Substanzgebrauch (STRING)" TEXT,
    "Aktueller Substanzgebrauch" TEXT,
    "Verhalten, exzessiv (STRING)" TEXT,
    "Verhalten, exzessiv" TEXT,
    "Bedeutung der Religiosität / Spiritualität [S]" TEXT,
    "Freitext Kontextdaten (STRING)" TEXT,
    "Antrieb [F] (STRING)" TEXT,
    "Antrieb [F]" TEXT,
    "column_391" TEXT,
    "column_392" TEXT,
    "Psychomotorik [F] (STRING)" TEXT,
    "Psychomotorik [F]" TEXT,
    "column_395" TEXT,
    "column_396" TEXT,
    "Alltag planen [F]" TEXT,
    "column_398" TEXT,
    "column_399" TEXT,
    "Alltagsplanung umsetzen [F]" TEXT,
    "column_401" TEXT,
    "column_402" TEXT,
    "Fähigkeit sich zu beschäftigen [F] (STRING)" TEXT,
    "Fähigkeit sich zu beschäftigen [F]" TEXT,
    "column_405" TEXT,
    "column_406" TEXT,
    "Schlafstörungen [F] (STRING)" TEXT,
    "Schlafstörungen [F]" TEXT,
    "column_409" TEXT,
    "column_410" TEXT,
    "Körperpflege [F]" TEXT,
    "column_412" TEXT,
    "column_413" TEXT,
    "Kleiden [F]" TEXT,
    "column_415" TEXT,
    "column_416" TEXT,
    "Fußstatus [F]" TEXT,
    "column_418" TEXT,
    "column_419" TEXT,
    "Freitext Kategorie Aktivität & Ruhe (STRING)" TEXT,
    "Fähigkeit neue Beziehungen zu Gleichaltrigen einzugehen [F]" TEXT,
    "column_422" TEXT,
    "column_423" TEXT,
    "Fähigkeit neue Beziehungen einzugehen [F]" TEXT,
    "column_425" TEXT,
    "column_426" TEXT,
    "Vorhandene Beziehungen aufrecht erhalten [F]" TEXT,
    "column_428" TEXT,
    "column_429" TEXT,
    "Soziale Interaktion [F]" TEXT,
    "column_431" TEXT,
    "column_432" TEXT,
    "Rollenverhalten (inter-personell) [F]" TEXT,
    "column_434" TEXT,
    "column_435" TEXT,
    "Rollenstress (intra-personell) [D]" TEXT,
    "column_437" TEXT,
    "column_438" TEXT,
    "Soziale Unterstützung [F]" TEXT,
    "column_440" TEXT,
    "column_441" TEXT,
    "Unterstützungsempfinden [S]" TEXT,
    "column_443" TEXT,
    "column_444" TEXT,
    "Freitext Kategorie Rollen & Beziehungen (STRING)" TEXT,
    "Gefühl der Zuversicht [D]" TEXT,
    "column_447" TEXT,
    "column_448" TEXT,
    "Gefühl der Hoffnung [D]" TEXT,
    "column_450" TEXT,
    "column_451" TEXT,
    "Grundstimmung [F] (STRING)" TEXT,
    "Grundstimmung [F]" TEXT,
    "column_454" TEXT,
    "column_455" TEXT,
    "Vorherrschende Emotion [S] (STRING)" TEXT,
    "Vorherrschende Emotion [S]" TEXT,
    "Selbstwert [F]" TEXT,
    "column_459" TEXT,
    "column_460" TEXT,
    "Selbstmitgefühl [F]" TEXT,
    "column_462" TEXT,
    "column_463" TEXT,
    "Freitext Kategorie Selbstwahrnehmung (STRING)" TEXT,
    "Selbstwirksamkeit [F] (STRING)" TEXT,
    "Selbstwirksamkeit [F]" TEXT,
    "column_467" TEXT,
    "column_468" TEXT,
    "Fähigkeit mit schwierigen Situationen umzugehen [F]" TEXT,
    "column_470" TEXT,
    "column_471" TEXT,
    "Fähigkeit mit Gefühlen umzugehen [F]" TEXT,
    "column_473" TEXT,
    "column_474" TEXT,
    "Adhärenz [F]" TEXT,
    "column_476" TEXT,
    "column_477" TEXT,
    "Angstformen [F] (STRING)" TEXT,
    "Angstformen [F]" TEXT,
    "Freitext Kategorie Coping & Stresstoleranz (STRING)" TEXT,
    "Lebenssinn [S]" TEXT,
    "column_482" TEXT,
    "column_483" TEXT,
    "Freitext Kategorie Lebensprinzipien (STRING)" TEXT,
    "Ernährungsverhalten [F] (STRING)" TEXT,
    "Ernährungsverhalten [F]" TEXT,
    "column_487" TEXT,
    "column_488" TEXT,
    "Enuresis" TEXT,
    "column_490" TEXT,
    "column_491" TEXT,
    "Merkfähigkeit [F]" TEXT,
    "column_493" TEXT,
    "column_494" TEXT,
    "Sinnestäuschungen [F] (STRING)" TEXT,
    "Sinnestäuschungen [F]" TEXT,
    "column_497" TEXT,
    "column_498" TEXT,
    "Wahnerleben [F] (STRING)" TEXT,
    "Wahnerleben [F]" TEXT,
    "column_501" TEXT,
    "column_502" TEXT,
    "Zwang [F] (STRING)" TEXT,
    "Zwang [F]" TEXT,
    "column_505" TEXT,
    "column_506" TEXT,
    "Freitext Wahrnehmung & Kognition (STRING)" TEXT,
    "Sexualität [D] (STRING)" TEXT,
    "Sexualität [D]" TEXT,
    "column_510" TEXT,
    "column_511" TEXT,
    "Geschlechtsidentität (STRING)" TEXT,
    "Geschlechtsidentität" TEXT,
    "column_514" TEXT,
    "column_515" TEXT,
    "Gesundheitliches Wohlbefinden [S]" TEXT,
    "column_517" TEXT,
    "column_518" TEXT,
    "Wissensstand [F]" TEXT,
    "column_520" TEXT,
    "column_521" TEXT,
    "Was hilft Dir/Ihnen, damit es Dir/Ihnen gut geht? [S] (STRING)" TEXT,
    "Was hilft Dir/Ihnen, damit es Dir/Ihnen gut geht? [S]" TEXT,
    "column_524" TEXT,
    "column_525" TEXT,
    "Warum geht es Dir/Ihnen jetzt nicht gut? [S] (STRING)" TEXT,
    "Warum geht es Dir/Ihnen jetzt nicht gut? [S]" TEXT,
    "column_528" TEXT,
    "column_529" TEXT,
    "Freitext Kategorie Gesundheitsförderung, Wohlbefinden und Sexualität (STRING)" TEXT,
    "Sozialverhalten [F]" TEXT,
    "column_532" TEXT,
    "column_533" TEXT,
    "Verhalten, fremdaggressiv [F]" TEXT,
    "Verhalten, selbstverletzend [F] (STRING)" TEXT,
    "Verhalten, selbstverletzend [F]" TEXT,
    "column_537" TEXT,
    "column_538" TEXT,
    "Suizidgedanken [D] (STRING)" TEXT,
    "Suizidgedanken [D]" TEXT,
    "column_541" TEXT,
    "column_542" TEXT,
    "Verhalten, suizidal [F]" TEXT,
    "column_544" TEXT,
    "column_545" TEXT,
    "Umgang mit Wut [S] (STRING)" TEXT,
    "Umgang mit Wut [S]" TEXT,
    "Freitext Kategorie Sicherheit & Schutz (STRING)" TEXT,
    "Elternbeteiligung" TEXT,
    "column_550" TEXT,
    "column_551" TEXT,
    "Fähigkeit Unterstützung zu leisten [F]" TEXT,
    "column_553" TEXT,
    "column_554" TEXT,
    "Unterstützung zur Erziehung [F] (STRING)" TEXT,
    "Unterstützung zur Erziehung [F]" TEXT,
    "column_557" TEXT,
    "column_558" TEXT,
    "Abklärungserfordernis Suizidalität" TEXT,
    "Abklärungserfordernis Gewaltpotenzial" TEXT,
    "SFI" TEXT,
    "Treppen steigen" TEXT,
    "column_563" TEXT,
    "column_564" TEXT,
    "Erinnerungsfähigkeit" TEXT,
    "column_566" TEXT,
    "column_567" TEXT,
    "Fähigkeit zur alltäglichen Lebensführung" TEXT,
    "column_569" TEXT,
    "column_570" TEXT,
    "Fähigkeit zur Haushaltsführung" TEXT,
    "column_572" TEXT,
    "column_573" TEXT,
    "Fähigkeit Aktivitäten außerhalb zu tätigen" TEXT,
    "column_575" TEXT,
    "column_576" TEXT,
    "Fähigkeit situationsangemessen zu entscheiden" TEXT,
    "column_578" TEXT,
    "column_579" TEXT,
    "Fähigkeit sich zu beschäftigen" TEXT,
    "column_581" TEXT,
    "column_582" TEXT,
    "Langzeitbeatmung" TEXT,
    "Abklärungserfordernis Depression" TEXT,
    "Dekubitus_interne Referenz" TEXT,
    "Dekubitus_interne Referenz__2" TEXT,
    "Wunden/ path. Hautveränderungen_interne Referenz" TEXT,
    "Wunden/ path. Hautveränderungen_interne Referenz__2" TEXT
);

-- Source: epaCC-START-Hack-2026-main/Endtestdaten_mit_Fehlern_ einheitliche ID/synth_cases_icd10_ops.csv
-- Encoding: utf-8-sig, Delimiter: ',', Header detected: True, Sample data rows: 1000
DROP TABLE IF EXISTS "synth_cases_icd10_ops";
CREATE TABLE "synth_cases_icd10_ops" (
    "CaseID" TEXT,
    "PatientID" TEXT,
    "Station" TEXT,
    "Aufnahmedatum" TEXT,
    "Entlassungsdatum" TEXT,
    "Verweildauer_Tage" TEXT,
    "ICD10_Haupt" TEXT,
    "ICD10_Haupt_Bezeichnung" TEXT,
    "ICD10_Neben" TEXT,
    "ICD10_Neben_Bezeichnung" TEXT,
    "OPS_Code" TEXT,
    "OPS_Bezeichnung" TEXT
);

-- Source: epaCC-START-Hack-2026-main/Endtestdaten_mit_Fehlern_ einheitliche ID/synth_device_motion_fall.csv
-- Encoding: utf-8-sig, Delimiter: ',', Header detected: True, Sample data rows: 40000
DROP TABLE IF EXISTS "synth_device_motion_fall";
CREATE TABLE "synth_device_motion_fall" (
    "patient_id" TEXT,
    "timestamp" TEXT,
    "movement_index_0_100" TEXT,
    "micro_movements_count" TEXT,
    "bed_exit_detected_0_1" TEXT,
    "fall_event_0_1" TEXT,
    "impact_magnitude_g" TEXT,
    "post_fall_immobility_minutes" TEXT,
    "column_9" TEXT
);

-- Source: epaCC-START-Hack-2026-main/Endtestdaten_mit_Fehlern_ einheitliche ID/synth_device_raw_1hz_motion_fall.csv
-- Encoding: utf-8-sig, Delimiter: ',', Header detected: True, Sample data rows: 150000
DROP TABLE IF EXISTS "synth_device_raw_1hz_motion_fall";
CREATE TABLE "synth_device_raw_1hz_motion_fall" (
    "PatientID" TEXT,
    "DeviceID" TEXT,
    "Timestamp" TEXT,
    "BedOccupied" TEXT,
    "MovementScore" TEXT,
    "AccelX" TEXT,
    "AccelY" TEXT,
    "AccelZ" TEXT,
    "AccelMag" TEXT,
    "PressZ1" TEXT,
    "PressZ2" TEXT,
    "PressZ3" TEXT,
    "PressZ4" TEXT,
    "BedExit" TEXT,
    "BedReturn" TEXT,
    "FallEvent" TEXT,
    "ImpactMag" TEXT,
    "EventID" TEXT,
    "column_19" TEXT
);

-- Source: epaCC-START-Hack-2026-main/Endtestdaten_mit_Fehlern_ einheitliche ID/synth_labs.csv
-- Encoding: utf-8-sig, Delimiter: ',', Header detected: True, Sample data rows: 5000
DROP TABLE IF EXISTS "synth_labs";
CREATE TABLE "synth_labs" (
    "CaseID" TEXT,
    "PID" TEXT,
    "Gender" TEXT,
    "Age" TEXT,
    "SpecDT" TEXT,
    "Na" TEXT,
    "Na_flag" TEXT,
    "Na_low" INTEGER,
    "Na_high" INTEGER,
    "K" TEXT,
    "K_flag" TEXT,
    "K_low" REAL,
    "K_high" REAL,
    "Creat" TEXT,
    "Creat_flag" TEXT,
    "Creat_low" REAL,
    "Creat_high" REAL,
    "eGFR" TEXT,
    "eGFR_flag" TEXT,
    "eGFR_low" INTEGER,
    "eGFR_high" INTEGER,
    "Gluc" TEXT,
    "Gluc_flag" TEXT,
    "Gluc_low" INTEGER,
    "Gluc_high" INTEGER,
    "Hb" TEXT,
    "Hb_flag" TEXT,
    "Hb_low" REAL,
    "Hb_high" REAL,
    "WBC" TEXT,
    "WBC_flag" TEXT,
    "WBC_low" REAL,
    "WBC_high" REAL,
    "PLT" TEXT,
    "PLT_flag" TEXT,
    "PLT_low" INTEGER,
    "PLT_high" INTEGER,
    "CRP" TEXT,
    "CRP_flag" TEXT,
    "CRP_low" REAL,
    "CRP_high" REAL,
    "ALT" TEXT,
    "ALT_flag" TEXT,
    "ALT_low" INTEGER,
    "ALT_high" INTEGER,
    "AST" TEXT,
    "AST_flag" TEXT,
    "AST_low" INTEGER,
    "AST_high" INTEGER,
    "Bili" TEXT,
    "Bili_flag" TEXT,
    "Bili_low" REAL,
    "Bili_high" REAL,
    "Alb" TEXT,
    "Alb_flag" TEXT,
    "Alb_low" REAL,
    "Alb_high" REAL,
    "INR" TEXT,
    "INR_flag" TEXT,
    "INR_low" REAL,
    "INR_high" REAL,
    "Lact" TEXT,
    "Lact_flag" TEXT,
    "Lact_low" REAL,
    "Lact_high" REAL
);

-- Source: epaCC-START-Hack-2026-main/Endtestdaten_mit_Fehlern_ einheitliche ID/synth_medication_raw_inpatient.csv
-- Encoding: utf-8-sig, Delimiter: ',', Header detected: True, Sample data rows: 25000
DROP TABLE IF EXISTS "synth_medication_raw_inpatient";
CREATE TABLE "synth_medication_raw_inpatient" (
    "rec_type" TEXT,
    "pat_id" TEXT,
    "enc_id" TEXT,
    "station" TEXT,
    "aufnahme_dt" TEXT,
    "entlassung_dt" TEXT,
    "order_id" TEXT,
    "uuid" TEXT,
    "atc_code" TEXT,
    "medikament" TEXT,
    "applikation" TEXT,
    "dosis" TEXT,
    "einheit" TEXT,
    "haeufigkeit" TEXT,
    "start_dt" TEXT,
    "stop_dt" TEXT,
    "bei_bedarf" TEXT,
    "indikation" TEXT,
    "verschreiber" TEXT,
    "bestellung_status" TEXT,
    "gabe_dt" TEXT,
    "gegebene_dosis" TEXT,
    "gabe_einheit" TEXT,
    "gabe_status" TEXT,
    "notiz" TEXT
);

-- Source: epaCC-START-Hack-2026-main/Endtestdaten_mit_Fehlern_ einheitliche ID/synth_nursing_daily_reports.csv
-- Encoding: utf-8-sig, Delimiter: ',', Header detected: True, Sample data rows: 2000
DROP TABLE IF EXISTS "synth_nursing_daily_reports";
CREATE TABLE "synth_nursing_daily_reports" (
    "CaseID" TEXT,
    "PatientID" TEXT,
    "Ward" TEXT,
    "ReportDate" TEXT,
    "Shift" TEXT,
    "NursingNote" TEXT
);
